M48
; DRILL file {KiCad 9.0.0} date 2025-05-15T06:11:26+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-15T06:11:26+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.6106Y-2.2681
X5.8381Y-2.2681
T2
X5.2323Y-2.1317
X5.3504Y-2.1317
M30
